(function (global) {
  'use strict';
  const { c, callout, exercise, tbl, flow, slide: s, objectives, lab, checklist, quiz } = global.DL;

  global.SLIDES.push(
    s('پروژه عملی', 'پروژه MiniShop Blog', 'یک سایت واقعی: مجله محتوایی + فروشگاه با سبد خرید و سفارش.', `
      <p class="lead">از این اسلاید تا پایان بخش، یک پروژه کامل و قابل انتشار می‌سازیم. هر مرحله کد کامل، دلیل تصمیم‌ها و یک نقطه کنترل دارد. هیچ مرحله‌ای را رد نکنید.</p>
      ${objectives([
        'یک پروژه چند-app با Custom User از صفر بسازید.',
        'مجله (مقاله، دسته، نظر) و فروشگاه (محصول، سبد، سفارش) را پیاده کنید.',
        'سبد خرید مبتنی بر session و ثبت سفارش تراکنشی بنویسید.',
        'دسترسی‌ها را امن کنید و صفحات خطای اختصاصی بسازید.',
        'برای هر بخش تست بنویسید و پروژه را برای انتشار آماده کنید.',
      ])}
      ${tbl(['App', 'مسئولیت', 'مدل‌ها'], [
        ['<code>accounts</code>', 'کاربر، ثبت‌نام، ورود، داشبورد.', '<code>User</code>'],
        ['<code>blog</code>', 'مقاله، دسته‌بندی، نظر، جست‌وجو.', '<code>Category</code>، <code>Post</code>، <code>Comment</code>'],
        ['<code>shop</code>', 'محصول، سبد خرید، سفارش.', '<code>ProductCategory</code>، <code>Product</code>، <code>Order</code>، <code>OrderItem</code>'],
      ])}
      ${flow(['accounts', 'blog', 'shop', 'سبد', 'سفارش', 'انتشار'])}
      ${callout('info', 'قرارداد پول در این پروژه', 'قیمت‌ها را با <code>PositiveIntegerField</code> و به واحد <strong>تومان</strong> ذخیره می‌کنیم؛ چون در ایران قیمت‌ها معمولا صحیح‌اند. اگر دامنه شما اعشار دارد (مثلا دلار)، همان‌جا <code>DecimalField</code> بگذارید. در هیچ حالتی <code>FloatField</code> نه.')}
    `),

    s('پروژه عملی', 'مرحله ۱: اسکلت پروژه و Custom User', 'اولین migrate باید بعد از ساخت مدل کاربر انجام شود.', `
      ${lab('راه‌اندازی پایه', 'زمان: ۲۰ دقیقه', [
        { do: c('bash', [
            'mkdir minishop && cd minishop',
            'python3 -m venv .venv && source .venv/bin/activate',
            'pip install "django>=5.0,<6.0" pillow',
            'django-admin startproject config .',
            'python manage.py startapp accounts',
            'python manage.py startapp blog',
            'python manage.py startapp shop',
          ], 'ساخت ساختار') },
        { do: c('python', [
            '# accounts/models.py',
            'from django.contrib.auth.models import AbstractUser',
            'from django.db import models',
            '',
            '',
            'class User(AbstractUser):',
            '    phone = models.CharField(max_length=15, blank=True)',
            '    bio = models.TextField(blank=True)',
            '',
            '    def __str__(self):',
            '        return self.username',
          ], 'accounts/models.py'), why: 'اگر این کار را بعد از اولین <code>migrate</code> انجام دهید، مجبور به حذف کل دیتابیس می‌شوید.' },
        { do: c('python', [
            '# config/settings.py',
            'INSTALLED_APPS = [',
            '    "django.contrib.admin",',
            '    "django.contrib.auth",',
            '    "django.contrib.contenttypes",',
            '    "django.contrib.sessions",',
            '    "django.contrib.messages",',
            '    "django.contrib.staticfiles",',
            '    "django.contrib.humanize",',
            '    "accounts",',
            '    "blog",',
            '    "shop",',
            ']',
            '',
            'AUTH_USER_MODEL = "accounts.User"',
            '',
            'LANGUAGE_CODE = "fa-ir"',
            'TIME_ZONE = "Asia/Tehran"',
            'USE_I18N = True',
            'USE_TZ = True',
            '',
            'TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]',
            '',
            'STATIC_URL = "static/"',
            'STATICFILES_DIRS = [BASE_DIR / "static"]',
            'STATIC_ROOT = BASE_DIR / "staticfiles"',
            '',
            'MEDIA_URL = "media/"',
            'MEDIA_ROOT = BASE_DIR / "media"',
            '',
            'LOGIN_URL = "accounts:login"',
            'LOGIN_REDIRECT_URL = "accounts:dashboard"',
            'LOGOUT_REDIRECT_URL = "blog:home"',
          ], 'config/settings.py') },
        { do: c('bash', ['python manage.py makemigrations', 'python manage.py migrate', 'python manage.py createsuperuser'], 'اولین migrate') },
      ], '<p><code>python manage.py runserver</code> بالا بیاید و <code>/admin/</code> با کاربر ساخته‌شده باز شود. در admin بخش <strong>Users</strong> باید مدل شما باشد نه مدل پیش‌فرض Django.</p>')}
      ${callout('danger', 'اگر migrate را زودتر اجرا کردید', 'خطای <code>Cannot change AUTH_USER_MODEL</code> می‌گیرید. در این مرحله ساده‌ترین راه: <code>db.sqlite3</code> و پوشه‌های <code>migrations/</code> (به‌جز <code>__init__.py</code>) را پاک کنید و از نو migrate بزنید. در پروژه واقعی چنین چیزی ممکن نیست — به همین دلیل از روز اول انجامش می‌دهیم.')}
    `),

    s('پروژه عملی', 'مرحله ۲: urls اصلی و قالب پایه', 'اسکلت مسیرها و ظاهر مشترک همه صفحات.', `
      ${c('python', [
        '# config/urls.py',
        'from django.conf import settings',
        'from django.conf.urls.static import static',
        'from django.contrib import admin',
        'from django.urls import include, path',
        '',
        'urlpatterns = [',
        '    path("admin/", admin.site.urls),',
        '    path("accounts/", include("accounts.urls")),',
        '    path("shop/", include("shop.urls")),',
        '    path("", include("blog.urls")),        # ← ریشه سایت، آخر از همه',
        ']',
        '',
        'if settings.DEBUG:',
        '    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)',
      ], 'config/urls.py')}
      ${c('html', [
        '<!-- templates/base.html -->',
        '{% load static %}',
        '<!doctype html>',
        '<html lang="fa" dir="rtl">',
        '<head>',
        '  <meta charset="utf-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1">',
        '  <title>{% block title %}MiniShop Blog{% endblock %}</title>',
        '  <link rel="stylesheet" href="{% static "css/style.css" %}">',
        '</head>',
        '<body>',
        '  <header class="site-header">',
        '    <nav>',
        '      <a href="{% url "blog:home" %}">خانه</a>',
        '      <a href="{% url "blog:post_list" %}">مقاله‌ها</a>',
        '      <a href="{% url "shop:product_list" %}">فروشگاه</a>',
        '      <a href="{% url "shop:cart_detail" %}">سبد خرید ({{ cart|length|default:"۰" }})</a>',
        '',
        '      {% if user.is_authenticated %}',
        '        <a href="{% url "accounts:dashboard" %}">{{ user.username }}</a>',
        '        <form method="post" action="{% url "accounts:logout" %}" class="inline">',
        '          {% csrf_token %}<button type="submit">خروج</button>',
        '        </form>',
        '      {% else %}',
        '        <a href="{% url "accounts:login" %}">ورود</a>',
        '        <a href="{% url "accounts:signup" %}">ثبت‌نام</a>',
        '      {% endif %}',
        '    </nav>',
        '  </header>',
        '',
        '  {% include "partials/messages.html" %}',
        '',
        '  <main class="container">{% block content %}{% endblock %}</main>',
        '',
        '  <footer>© MiniShop Blog</footer>',
        '</body>',
        '</html>',
      ], 'templates/base.html')}
      ${c('html', [
        '<!-- templates/partials/messages.html -->',
        '{% if messages %}',
        '  <ul class="messages">',
        '    {% for message in messages %}',
        '      <li class="msg {{ message.tags }}">{{ message }}</li>',
        '    {% endfor %}',
        '  </ul>',
        '{% endif %}',
      ], 'templates/partials/messages.html')}
      ${callout('warn', 'هنوز لینک‌ها کار نمی‌کنند', 'در این مرحله <code>{% url %}</code>ها خطای <code>NoReverseMatch</code> می‌دهند چون هنوز مسیرها ساخته نشده‌اند. طبیعی است — در مرحله بعد ساخته می‌شوند. اگر می‌خواهید همین حالا صفحه را ببینید، موقتا فقط <code>blog:home</code> را بگذارید.')}
    `),

    s('پروژه عملی', 'مرحله ۳: مدل‌های Blog', 'مقاله، دسته‌بندی و نظر — همراه با QuerySet سفارشی.', `
      ${c('python', [
        '# blog/models.py',
        'from django.conf import settings',
        'from django.db import models',
        'from django.urls import reverse',
        'from django.utils import timezone',
        'from django.utils.text import slugify',
        '',
        '',
        'class Category(models.Model):',
        '    title = models.CharField(max_length=120, verbose_name="عنوان")',
        '    slug = models.SlugField(max_length=140, unique=True, allow_unicode=True)',
        '',
        '    class Meta:',
        '        verbose_name = "دسته‌بندی"',
        '        verbose_name_plural = "دسته‌بندی‌ها"',
        '',
        '    def __str__(self):',
        '        return self.title',
        '',
        '    def get_absolute_url(self):',
        '        return reverse("blog:category", kwargs={"slug": self.slug})',
        '',
        '',
        'class PostQuerySet(models.QuerySet):',
        '    def published(self):',
        '        return self.filter(is_published=True, published_at__lte=timezone.now())',
        '',
        '    def with_relations(self):',
        '        return self.select_related("author", "category")',
        '',
        '',
        'class Post(models.Model):',
        '    author = models.ForeignKey(',
        '        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts"',
        '    )',
        '    category = models.ForeignKey(',
        '        Category, on_delete=models.PROTECT, related_name="posts"',
        '    )',
        '    title = models.CharField(max_length=200, verbose_name="عنوان")',
        '    slug = models.SlugField(max_length=220, unique=True, allow_unicode=True, blank=True)',
        '    summary = models.CharField(max_length=300, verbose_name="خلاصه")',
        '    body = models.TextField(verbose_name="متن")',
        '    cover = models.ImageField(upload_to="posts/%Y/%m/", blank=True)',
        '    is_published = models.BooleanField(default=False)',
        '    published_at = models.DateTimeField(default=timezone.now)',
        '    created_at = models.DateTimeField(auto_now_add=True)',
        '    updated_at = models.DateTimeField(auto_now=True)',
        '',
        '    objects = PostQuerySet.as_manager()',
        '',
        '    class Meta:',
        '        ordering = ["-published_at"]',
        '        indexes = [models.Index(fields=["-published_at"]), models.Index(fields=["slug"])]',
        '',
        '    def __str__(self):',
        '        return self.title',
        '',
        '    def save(self, *args, **kwargs):',
        '        if not self.slug:',
        '            self.slug = slugify(self.title, allow_unicode=True)',
        '        super().save(*args, **kwargs)',
        '',
        '    def get_absolute_url(self):',
        '        return reverse("blog:post_detail", kwargs={"slug": self.slug})',
        '',
        '',
        'class Comment(models.Model):',
        '    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")',
        '    author = models.ForeignKey(',
        '        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"',
        '    )',
        '    body = models.TextField(max_length=1000, verbose_name="نظر")',
        '    is_approved = models.BooleanField(default=False)',
        '    created_at = models.DateTimeField(auto_now_add=True)',
        '',
        '    class Meta:',
        '        ordering = ["-created_at"]',
        '',
        '    def __str__(self):',
        '        return f"{self.author} روی {self.post}"',
      ], 'blog/models.py')}
      ${callout('info', 'چرا published_at جدا از created_at؟', '<code>created_at</code> یعنی «کِی ساخته شد» و <code>published_at</code> یعنی «کِی باید دیده شود». با این جدایی می‌توانید مقاله را از قبل بنویسید و برای انتشار زمان‌بندی کنید — دقیقا کاری که <code>published()</code> انجام می‌دهد.')}
    `),

    s('پروژه عملی', 'مرحله ۴: Admin و داده اولیه', 'بدون داده، هیچ صفحه‌ای قابل بررسی نیست.', `
      ${c('python', [
        '# blog/admin.py',
        'from django.contrib import admin',
        'from .models import Category, Comment, Post',
        '',
        '',
        '@admin.register(Category)',
        'class CategoryAdmin(admin.ModelAdmin):',
        '    list_display = ("title", "slug")',
        '    prepopulated_fields = {"slug": ("title",)}',
        '    search_fields = ("title",)',
        '',
        '',
        'class CommentInline(admin.TabularInline):',
        '    model = Comment',
        '    extra = 0',
        '',
        '',
        '@admin.register(Post)',
        'class PostAdmin(admin.ModelAdmin):',
        '    list_display = ("title", "author", "category", "is_published", "published_at")',
        '    list_filter = ("is_published", "category")',
        '    search_fields = ("title", "summary", "body")',
        '    list_editable = ("is_published",)',
        '    autocomplete_fields = ("category",)',
        '    list_select_related = ("author", "category")',
        '    inlines = [CommentInline]',
        '',
        '',
        '@admin.register(Comment)',
        'class CommentAdmin(admin.ModelAdmin):',
        '    list_display = ("post", "author", "is_approved", "created_at")',
        '    list_filter = ("is_approved",)',
        '    actions = ["approve"]',
        '',
        '    @admin.action(description="تایید نظرهای انتخاب‌شده")',
        '    def approve(self, request, queryset):',
        '        updated = queryset.update(is_approved=True)',
        '        self.message_user(request, f"{updated} نظر تایید شد.")',
      ], 'blog/admin.py')}
      ${callout('warn', 'prepopulated_fields و عنوان فارسی', 'اسکریپت admin برای ساخت خودکار slug فقط حروف لاتین را نگه می‌دارد؛ با عنوان فارسی، فیلد slug خالی می‌ماند. یا slug را دستی (به لاتین) بنویسید، یا مثل مدل <code>Post</code> در متد <code>save()</code> با <code>slugify(..., allow_unicode=True)</code> بسازید و <code>prepopulated_fields</code> را بردارید.')}
      ${c('python', [
        '# blog/management/commands/seed.py',
        '# پوشه‌های management/ و management/commands/ باید __init__.py داشته باشند',
        'from django.contrib.auth import get_user_model',
        'from django.core.management.base import BaseCommand',
        'from blog.models import Category, Post',
        'from shop.models import Product, ProductCategory',
        '',
        '',
        'class Command(BaseCommand):',
        '    help = "ساخت داده نمونه برای توسعه"',
        '',
        '    def handle(self, *args, **options):',
        '        user, _ = get_user_model().objects.get_or_create(',
        '            username="demo", defaults={"is_staff": True},',
        '        )',
        '',
        '        blog_cat, _ = Category.objects.get_or_create(',
        '            slug="django", defaults={"title": "جنگو"},',
        '        )',
        '        for i in range(1, 9):',
        '            Post.objects.get_or_create(',
        '                slug=f"sample-post-{i}",',
        '                defaults={',
        '                    "title": f"مقاله نمونه شماره {i}",',
        '                    "summary": "خلاصه کوتاه مقاله نمونه.",',
        '                    "body": "متن کامل مقاله نمونه برای آزمایش صفحات.",',
        '                    "author": user, "category": blog_cat, "is_published": True,',
        '                },',
        '            )',
        '',
        '        shop_cat, _ = ProductCategory.objects.get_or_create(',
        '            slug="digital", defaults={"title": "کالای دیجیتال"},',
        '        )',
        '        for i in range(1, 7):',
        '            Product.objects.get_or_create(',
        '                slug=f"sample-product-{i}",',
        '                defaults={',
        '                    "name": f"محصول نمونه {i}", "description": "توضیح محصول.",',
        '                    "price": 250_000 * i, "stock": 5,',
        '                    "category": shop_cat, "is_active": True,',
        '                },',
        '            )',
        '',
        '        self.stdout.write(self.style.SUCCESS("داده نمونه ساخته شد."))',
      ], 'blog/management/commands/seed.py')}
      ${c('bash', ['python manage.py makemigrations', 'python manage.py migrate', 'python manage.py seed'], 'اجرا')}
      ${callout('tip', 'نقطه کنترل', 'در <code>/admin/</code> باید ۸ مقاله و ۶ محصول ببینید. اگر <code>seed</code> پیدا نشد، وجود <code>__init__.py</code> در هر دو پوشه <code>management</code> و <code>commands</code> را بررسی کنید.')}
    `),

    s('پروژه عملی', 'مرحله ۵: صفحات Blog با صفحه‌بندی', 'خانه، فهرست، جزئیات و دسته‌بندی.', `
      ${c('python', [
        '# blog/urls.py',
        'from django.urls import path',
        'from . import views',
        '',
        'app_name = "blog"',
        '',
        'urlpatterns = [',
        '    path("", views.home, name="home"),',
        '    path("posts/", views.post_list, name="post_list"),',
        '    path("search/", views.search, name="search"),',
        '    path("category/<slug:slug>/", views.category_detail, name="category"),',
        '    path("posts/<slug:slug>/", views.post_detail, name="post_detail"),',
        '    path("posts/<slug:slug>/comment/", views.comment_create, name="comment_create"),',
        ']',
      ], 'blog/urls.py')}
      ${c('python', [
        '# blog/views.py',
        'from django.core.paginator import Paginator',
        'from django.shortcuts import get_object_or_404, render',
        'from .forms import CommentForm',
        'from .models import Category, Post',
        '',
        '',
        'def home(request):',
        '    posts = Post.objects.published().with_relations()[:6]',
        '    return render(request, "blog/home.html", {"posts": posts})',
        '',
        '',
        'def post_list(request):',
        '    posts = Post.objects.published().with_relations()',
        '    page = Paginator(posts, 6).get_page(request.GET.get("page"))',
        '    return render(request, "blog/post_list.html", {"page_obj": page})',
        '',
        '',
        'def post_detail(request, slug):',
        '    post = get_object_or_404(',
        '        Post.objects.published().with_relations(), slug=slug,',
        '    )',
        '    comments = post.comments.filter(is_approved=True).select_related("author")',
        '    return render(request, "blog/post_detail.html", {',
        '        "post": post,',
        '        "comments": comments,',
        '        "form": CommentForm(),',
        '    })',
        '',
        '',
        'def category_detail(request, slug):',
        '    category = get_object_or_404(Category, slug=slug)',
        '    posts = category.posts.published().with_relations()',
        '    page = Paginator(posts, 6).get_page(request.GET.get("page"))',
        '    return render(request, "blog/category_detail.html", {',
        '        "category": category, "page_obj": page,',
        '    })',
      ], 'blog/views.py')}
      ${c('html', [
        '<!-- templates/blog/post_list.html -->',
        '{% extends "base.html" %}',
        '',
        '{% block title %}مقاله‌ها{% endblock %}',
        '',
        '{% block content %}',
        '  <h1>مقاله‌ها</h1>',
        '  <div class="grid">',
        '    {% for post in page_obj %}',
        '      {% include "blog/partials/post_card.html" %}',
        '    {% empty %}',
        '      <p>هنوز مقاله‌ای منتشر نشده است.</p>',
        '    {% endfor %}',
        '  </div>',
        '  {% include "partials/pagination.html" %}',
        '{% endblock %}',
      ], 'templates/blog/post_list.html')}
      ${c('html', [
        '<!-- templates/partials/pagination.html -->',
        '{% if page_obj.has_other_pages %}',
        '  <nav class="pagination">',
        '    {% if page_obj.has_previous %}',
        '      <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>',
        '    {% endif %}',
        '    <span>صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}</span>',
        '    {% if page_obj.has_next %}',
        '      <a href="?page={{ page_obj.next_page_number }}">بعدی</a>',
        '    {% endif %}',
        '  </nav>',
        '{% endif %}',
      ], 'templates/partials/pagination.html')}
      ${callout('info', 'ارجاع به جلو', 'در این مرحله <code>CommentForm</code> و مسیر <code>comment_create</code> هنوز ساخته نشده‌اند؛ آن‌ها را در مرحله ۷ می‌سازیم. تا آن موقع می‌توانید آن دو خط را موقتا کامنت کنید تا سرور بالا بیاید.')}
      ${callout('warn', 'صفحه‌بندی و جست‌وجو با هم', 'اگر صفحه فیلتر دارد، در لینک صفحه‌بندی باید پارامترها حفظ شوند؛ وگرنه با رفتن به صفحه ۲، فیلتر از بین می‌رود. راه ساده: <code>?page={{ page_obj.next_page_number }}&q={{ query }}</code>.')}
    `),

    s('پروژه عملی', 'مرحله ۶: جست‌وجو و کارت مقاله', 'جست‌وجوی چندفیلدی با Q.', `
      ${c('python', [
        '# blog/views.py',
        'from django.db.models import Q',
        '',
        '',
        'def search(request):',
        '    query = request.GET.get("q", "").strip()',
        '    posts = Post.objects.none()',
        '',
        '    if query:',
        '        posts = Post.objects.published().with_relations().filter(',
        '            Q(title__icontains=query)',
        '            | Q(summary__icontains=query)',
        '            | Q(body__icontains=query)',
        '        )',
        '',
        '    page = Paginator(posts, 6).get_page(request.GET.get("page"))',
        '    return render(request, "blog/search.html", {"query": query, "page_obj": page})',
      ], 'view جست‌وجو')}
      ${c('html', [
        '<!-- templates/blog/search.html -->',
        '{% extends "base.html" %}',
        '',
        '{% block content %}',
        '  <form method="get" action="{% url "blog:search" %}" class="search-form">',
        '    <input type="search" name="q" value="{{ query }}" placeholder="جست‌وجو در مقاله‌ها...">',
        '    <button type="submit">جست‌وجو</button>',
        '  </form>',
        '',
        '  {% if query %}',
        '    <p>{{ page_obj.paginator.count }} نتیجه برای «{{ query }}»</p>',
        '    {% for post in page_obj %}',
        '      {% include "blog/partials/post_card.html" %}',
        '    {% empty %}',
        '      <p>نتیجه‌ای پیدا نشد.</p>',
        '    {% endfor %}',
        '  {% endif %}',
        '{% endblock %}',
      ], 'templates/blog/search.html')}
      ${c('html', [
        '<!-- templates/blog/partials/post_card.html -->',
        '{% load humanize %}',
        '<article class="card">',
        '  {% if post.cover %}',
        '    <img src="{{ post.cover.url }}" alt="{{ post.title }}">',
        '  {% endif %}',
        '  <a class="tag" href="{{ post.category.get_absolute_url }}">{{ post.category.title }}</a>',
        '  <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>',
        '  <p>{{ post.summary }}</p>',
        '  <footer>',
        '    <span>{{ post.author.username }}</span>',
        '    <time>{{ post.published_at|date:"Y/m/d" }}</time>',
        '  </footer>',
        '</article>',
      ], 'templates/blog/partials/post_card.html')}
      ${callout('info', 'محدودیت icontains', 'این جست‌وجو ساده و قابل اتکاست ولی برای داده زیاد کند می‌شود و «جنگو» را با «جانگو» یکی نمی‌داند. قدم بعدی: <code>SearchVector</code> در PostgreSQL یا موتور جست‌وجو مثل Meilisearch.')}
      ${exercise('فیلتر محصول', 'متوسط', '<p>در فروشگاه اگر پارامتر <code>?category=slug</code> آمد، محصولات همان دسته را نشان دهید و در غیر این صورت همه را.</p>', c('python', [
        'def product_list(request):',
        '    products = Product.objects.active().select_related("category")',
        '    category_slug = request.GET.get("category")',
        '    if category_slug:',
        '        products = products.filter(category__slug=category_slug)',
        '    return render(request, "shop/product_list.html", {',
        '        "products": products,',
        '        "categories": ProductCategory.objects.all(),',
        '        "selected": category_slug,',
        '    })',
      ], 'راه‌حل'))}
    `),

    s('پروژه عملی', 'مرحله ۷: ثبت نظر', 'اولین فرم واقعی پروژه، با محافظت کامل.', `
      ${c('python', [
        '# blog/forms.py',
        'from django import forms',
        'from .models import Comment',
        '',
        '',
        'class CommentForm(forms.ModelForm):',
        '    class Meta:',
        '        model = Comment',
        '        fields = ["body"]          # فقط متن؛ نویسنده و مقاله از سرور می‌آیند',
        '        labels = {"body": "نظر شما"}',
        '        widgets = {',
        '            "body": forms.Textarea(attrs={"rows": 4, "placeholder": "نظرتان را بنویسید..."}),',
        '        }',
        '',
        '    def clean_body(self):',
        '        body = self.cleaned_data["body"].strip()',
        '        if len(body) < 5:',
        '            raise forms.ValidationError("نظر باید حداقل ۵ کاراکتر باشد.")',
        '        return body',
      ], 'blog/forms.py')}
      ${c('python', [
        '# blog/views.py',
        'from django.contrib import messages',
        'from django.contrib.auth.decorators import login_required',
        'from django.shortcuts import get_object_or_404, redirect, render',
        'from django.views.decorators.http import require_POST',
        '',
        '',
        '@login_required',
        '@require_POST',
        'def comment_create(request, slug):',
        '    post = get_object_or_404(Post.objects.published(), slug=slug)',
        '    form = CommentForm(request.POST)',
        '',
        '    if form.is_valid():',
        '        comment = form.save(commit=False)',
        '        comment.post = post                 # از URL',
        '        comment.author = request.user       # از session',
        '        comment.save()',
        '        messages.success(request, "نظر شما ثبت شد و پس از تایید نمایش داده می‌شود.")',
        '    else:',
        '        messages.error(request, "متن نظر معتبر نیست.")',
        '',
        '    return redirect(post.get_absolute_url() + "#comments")',
      ], 'view ثبت نظر')}
      ${c('html', [
        '<!-- بخش نظرها در templates/blog/post_detail.html -->',
        '<section id="comments">',
        '  <h2>نظرها ({{ comments|length }})</h2>',
        '',
        '  {% for comment in comments %}',
        '    <div class="comment">',
        '      <strong>{{ comment.author.username }}</strong>',
        '      <time>{{ comment.created_at|date:"Y/m/d" }}</time>',
        '      <p>{{ comment.body|linebreaks }}</p>',
        '    </div>',
        '  {% empty %}',
        '    <p>هنوز نظری ثبت نشده است.</p>',
        '  {% endfor %}',
        '',
        '  {% if user.is_authenticated %}',
        '    <form method="post" action="{% url "blog:comment_create" post.slug %}">',
        '      {% csrf_token %}',
        '      {{ form.body }}',
        '      {{ form.body.errors }}',
        '      <button type="submit">ثبت نظر</button>',
        '    </form>',
        '  {% else %}',
        '    <p><a href="{% url "accounts:login" %}?next={{ request.path }}">برای ثبت نظر وارد شوید</a></p>',
        '  {% endif %}',
        '</section>',
      ], 'قالب نظرها')}
      ${callout('danger', 'سه محافظت هم‌زمان', 'یک: <code>@require_POST</code> جلوی ثبت نظر با یک لینک ساده را می‌گیرد. دو: <code>@login_required</code> نظر ناشناس را رد می‌کند. سه: <code>author</code> و <code>post</code> در فرم نیستند و از سمت سرور پر می‌شوند تا کاربر نتواند نظر را به نام دیگری ثبت کند.')}
      ${callout('tip', 'چرا is_approved؟', 'نظر تاییدنشده به‌طور پیش‌فرض نمایش داده نمی‌شود؛ این ساده‌ترین سد در برابر اسپم است. تایید گروهی را در admin با action ساختیم.')}
    `),

    s('پروژه عملی', 'مرحله ۸: مدل‌های Shop', 'محصول، سفارش و آیتم سفارش.', `
      ${c('python', [
        '# shop/models.py',
        'from django.conf import settings',
        'from django.db import models',
        'from django.urls import reverse',
        'from django.utils.text import slugify',
        '',
        '',
        'class ProductCategory(models.Model):',
        '    title = models.CharField(max_length=120)',
        '    slug = models.SlugField(max_length=140, unique=True, allow_unicode=True)',
        '',
        '    class Meta:',
        '        verbose_name_plural = "Product categories"',
        '',
        '    def __str__(self):',
        '        return self.title',
        '',
        '',
        'class ProductQuerySet(models.QuerySet):',
        '    def active(self):',
        '        return self.filter(is_active=True)',
        '',
        '    def in_stock(self):',
        '        return self.active().filter(stock__gt=0)',
        '',
        '',
        'class Product(models.Model):',
        '    category = models.ForeignKey(',
        '        ProductCategory, on_delete=models.PROTECT, related_name="products"',
        '    )',
        '    name = models.CharField(max_length=180)',
        '    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, blank=True)',
        '    description = models.TextField()',
        '    image = models.ImageField(upload_to="products/%Y/%m/", blank=True)',
        '    price = models.PositiveIntegerField(help_text="به تومان")',
        '    stock = models.PositiveIntegerField(default=0)',
        '    is_active = models.BooleanField(default=True)',
        '    created_at = models.DateTimeField(auto_now_add=True)',
        '',
        '    objects = ProductQuerySet.as_manager()',
        '',
        '    class Meta:',
        '        ordering = ["-created_at"]',
        '        constraints = [',
        '            models.CheckConstraint(condition=models.Q(price__gt=0), name="product_price_gt_0"),',
        '        ]',
        '',
        '    def __str__(self):',
        '        return self.name',
        '',
        '    def save(self, *args, **kwargs):',
        '        if not self.slug:',
        '            self.slug = slugify(self.name, allow_unicode=True)',
        '        super().save(*args, **kwargs)',
        '',
        '    def get_absolute_url(self):',
        '        return reverse("shop:product_detail", kwargs={"slug": self.slug})',
        '',
        '',
        'class Order(models.Model):',
        '    class Status(models.TextChoices):',
        '        PENDING = "pending", "در انتظار پرداخت"',
        '        PAID = "paid", "پرداخت‌شده"',
        '        CANCELED = "canceled", "لغو شده"',
        '',
        '    user = models.ForeignKey(',
        '        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="orders"',
        '    )',
        '    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDING)',
        '    address = models.TextField(verbose_name="نشانی")',
        '    created_at = models.DateTimeField(auto_now_add=True)',
        '',
        '    class Meta:',
        '        ordering = ["-created_at"]',
        '',
        '    def __str__(self):',
        '        return f"سفارش #{self.pk}"',
        '',
        '    @property',
        '    def total(self):',
        '        return sum(item.subtotal for item in self.items.all())',
        '',
        '',
        'class OrderItem(models.Model):',
        '    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")',
        '    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name="order_items")',
        '    price = models.PositiveIntegerField(help_text="قیمت در لحظه خرید")',
        '    quantity = models.PositiveIntegerField(default=1)',
        '',
        '    @property',
        '    def subtotal(self):',
        '        return self.price * self.quantity',
      ], 'shop/models.py')}
      ${callout('info', 'چرا قیمت در OrderItem تکرار شده؟', 'قیمت محصول فردا عوض می‌شود، ولی فاکتور دیروز نباید تغییر کند. برای همین قیمت لحظه خرید در خود سفارش ثبت می‌شود. همین دلیل باعث می‌شود <code>on_delete=PROTECT</code> روی محصول بگذاریم — حذف محصول نباید تاریخچه فروش را خراب کند.')}
    `),

    s('پروژه عملی', 'مرحله ۹: سبد خرید مبتنی بر Session', 'کلاس Cart — قلب فروشگاه.', `
      <p>سبد خرید کاربر مهمان نباید در دیتابیس باشد. آن را در session نگه می‌داریم: فقط شناسه و تعداد ذخیره می‌شود و اطلاعات محصول در لحظه نمایش از دیتابیس خوانده می‌شود.</p>
      ${c('python', [
        '# shop/cart.py',
        'from .models import Product',
        '',
        '',
        'class Cart:',
        '    SESSION_KEY = "cart"',
        '',
        '    def __init__(self, request):',
        '        self.session = request.session',
        '        self.items = self.session.setdefault(self.SESSION_KEY, {})',
        '',
        '    def _save(self):',
        '        self.session[self.SESSION_KEY] = self.items',
        '        self.session.modified = True      # بدون این خط ذخیره نمی‌شود',
        '',
        '    def add(self, product, quantity=1, override=False):',
        '        key = str(product.id)             # کلید session باید رشته باشد',
        '        current = self.items.get(key, {"quantity": 0})',
        '        current["quantity"] = quantity if override else current["quantity"] + quantity',
        '        current["quantity"] = min(current["quantity"], product.stock)',
        '        self.items[key] = current',
        '        self._save()',
        '',
        '    def remove(self, product_id):',
        '        if self.items.pop(str(product_id), None) is not None:',
        '            self._save()',
        '',
        '    def clear(self):',
        '        self.items = {}',
        '        self._save()',
        '',
        '    def __iter__(self):',
        '        """محصولات را با یک query می‌خواند و آیتم کامل برمی‌گرداند."""',
        '        products = Product.objects.filter(id__in=self.items.keys())',
        '        for product in products:',
        '            quantity = self.items[str(product.id)]["quantity"]',
        '            yield {',
        '                "product": product,',
        '                "quantity": quantity,',
        '                "subtotal": product.price * quantity,',
        '            }',
        '',
        '    def __len__(self):',
        '        return sum(item["quantity"] for item in self.items.values())',
        '',
        '    @property',
        '    def total(self):',
        '        return sum(item["subtotal"] for item in self)',
      ], 'shop/cart.py')}
      ${tbl(['تصمیم طراحی', 'چرا'], [
        ['ذخیره فقط <code>id</code> و <code>quantity</code>', 'نام و قیمت در session کهنه می‌شوند؛ همیشه از دیتابیس بخوانید.'],
        ['کلید رشته‌ای', 'session به JSON تبدیل می‌شود و کلید عددی به رشته بدل می‌گردد.'],
        ['<code>__iter__</code> با یک query', 'جلوگیری از N+1 هنگام نمایش سبد.'],
        ['<code>min(quantity, product.stock)</code>', 'جلوگیری از سفارش بیش از موجودی.'],
        ['<code>session.modified = True</code>', 'تغییر داخل دیکشنری تودرتو خودکار تشخیص داده نمی‌شود.'],
      ])}
      ${c('python', [
        '# shop/context_processors.py — تا سبد در همه صفحات دیده شود',
        'from .cart import Cart',
        '',
        '',
        'def cart(request):',
        '    return {"cart": Cart(request)}',
        '',
        '',
        '# config/settings.py → TEMPLATES → OPTIONS → context_processors',
        '# "shop.context_processors.cart",',
      ], 'نمایش سبد در header')}
    `),

    s('پروژه عملی', 'مرحله ۱۰: مسیرها و viewهای فروشگاه', 'ترتیب urlpatterns اینجا حیاتی است.', `
      ${c('python', [
        '# shop/urls.py',
        'from django.urls import path',
        'from . import views',
        '',
        'app_name = "shop"',
        '',
        'urlpatterns = [',
        '    path("", views.product_list, name="product_list"),',
        '    # --- مسیرهای ثابت باید قبل از الگوی slug بیایند ---',
        '    path("cart/", views.cart_detail, name="cart_detail"),',
        '    path("cart/add/<int:product_id>/", views.cart_add, name="cart_add"),',
        '    path("cart/remove/<int:product_id>/", views.cart_remove, name="cart_remove"),',
        '    path("checkout/", views.checkout, name="checkout"),',
        '    path("orders/<int:pk>/", views.order_detail, name="order_detail"),',
        '    # --- الگوی عمومی، آخر از همه ---',
        '    path("<slug:slug>/", views.product_detail, name="product_detail"),',
        ']',
      ], 'shop/urls.py')}
      ${c('python', [
        '# shop/views.py',
        'from django.contrib import messages',
        'from django.shortcuts import get_object_or_404, redirect, render',
        'from django.views.decorators.http import require_POST',
        'from .cart import Cart',
        'from .models import Product, ProductCategory',
        '',
        '',
        'def product_list(request):',
        '    products = Product.objects.active().select_related("category")',
        '    category_slug = request.GET.get("category")',
        '    if category_slug:',
        '        products = products.filter(category__slug=category_slug)',
        '',
        '    return render(request, "shop/product_list.html", {',
        '        "products": products,',
        '        "categories": ProductCategory.objects.all(),',
        '        "selected": category_slug,',
        '    })',
        '',
        '',
        'def product_detail(request, slug):',
        '    product = get_object_or_404(Product.objects.active(), slug=slug)',
        '    return render(request, "shop/product_detail.html", {"product": product})',
        '',
        '',
        '@require_POST',
        'def cart_add(request, product_id):',
        '    product = get_object_or_404(Product.objects.active(), id=product_id)',
        '    quantity = int(request.POST.get("quantity", 1))',
        '',
        '    if product.stock < 1:',
        '        messages.error(request, "این محصول موجود نیست.")',
        '    else:',
        '        Cart(request).add(product, quantity=quantity)',
        '        messages.success(request, f"«{product.name}» به سبد اضافه شد.")',
        '',
        '    return redirect("shop:cart_detail")',
        '',
        '',
        '@require_POST',
        'def cart_remove(request, product_id):',
        '    Cart(request).remove(product_id)',
        '    messages.info(request, "محصول از سبد حذف شد.")',
        '    return redirect("shop:cart_detail")',
        '',
        '',
        'def cart_detail(request):',
        '    return render(request, "shop/cart_detail.html")   # cart از context processor می‌آید',
      ], 'shop/views.py')}
      ${c('html', [
        '<!-- templates/shop/cart_detail.html -->',
        '{% extends "base.html" %}',
        '{% load humanize %}',
        '',
        '{% block title %}سبد خرید{% endblock %}',
        '',
        '{% block content %}',
        '  <h1>سبد خرید</h1>',
        '',
        '  {% if cart|length %}',
        '    <table class="cart-table">',
        '      <thead>',
        '        <tr><th>محصول</th><th>تعداد</th><th>قیمت واحد</th><th>جمع</th><th></th></tr>',
        '      </thead>',
        '      <tbody>',
        '        {% for item in cart %}',
        '          <tr>',
        '            <td><a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a></td>',
        '            <td>{{ item.quantity }}</td>',
        '            <td>{{ item.product.price|intcomma }}</td>',
        '            <td>{{ item.subtotal|intcomma }}</td>',
        '            <td>',
        '              <form method="post" action="{% url "shop:cart_remove" item.product.id %}">',
        '                {% csrf_token %}',
        '                <button type="submit">حذف</button>',
        '              </form>',
        '            </td>',
        '          </tr>',
        '        {% endfor %}',
        '      </tbody>',
        '    </table>',
        '',
        '    <p class="total">جمع کل: {{ cart.total|intcomma }} تومان</p>',
        '    <a class="btn" href="{% url "shop:checkout" %}">ادامه و ثبت سفارش</a>',
        '  {% else %}',
        '    <p>سبد خرید خالی است.</p>',
        '    <a href="{% url "shop:product_list" %}">رفتن به فروشگاه</a>',
        '  {% endif %}',
        '{% endblock %}',
      ], 'templates/shop/cart_detail.html')}
      ${callout('danger', 'دو باگ رایج که اینجا رفع شده‌اند', 'یک: اگر مسیر <code>&lt;slug:slug&gt;</code> بالای <code>cart/</code> باشد، آدرس سبد به view محصول می‌رود و ۴۰۴ می‌گیرید. دو: اگر <code>cart_add</code> با GET قابل صدا زدن باشد، هر crawler می‌تواند سبد کاربران را پر کند — به همین دلیل <code>@require_POST</code> گذاشتیم.')}
    `),

    s('پروژه عملی', 'مرحله ۱۱: ثبت سفارش با تراکنش', 'مهم‌ترین قطعه منطق کسب‌وکار پروژه.', `
      ${flow(['سبد', 'فرم نشانی', 'تراکنش', 'کاهش موجودی', 'خالی‌کردن سبد', 'صفحه سفارش'])}
      ${c('python', [
        '# shop/forms.py',
        'from django import forms',
        'from .models import Order',
        '',
        '',
        'class CheckoutForm(forms.ModelForm):',
        '    class Meta:',
        '        model = Order',
        '        fields = ["address"]           # کاربر و وضعیت از سرور می‌آیند',
        '        widgets = {"address": forms.Textarea(attrs={"rows": 3})}',
      ], 'shop/forms.py')}
      ${c('python', [
        '# shop/services.py — منطق کسب‌وکار، جدا از view',
        'from django.db import transaction',
        'from django.db.models import F',
        'from .models import Order, OrderItem, Product',
        '',
        '',
        'class OutOfStock(Exception):',
        '    pass',
        '',
        '',
        '@transaction.atomic',
        'def place_order(*, user, cart, address):',
        '    """سفارش را می‌سازد و موجودی را کم می‌کند؛ همه یا هیچ."""',
        '    if len(cart) == 0:',
        '        raise ValueError("سبد خرید خالی است.")',
        '',
        '    order = Order.objects.create(user=user, address=address)',
        '',
        '    for item in cart:',
        '        product = item["product"]',
        '        quantity = item["quantity"]',
        '',
        '        # کاهش شرطی و اتمیک: فقط اگر موجودی کافی باشد',
        '        updated = Product.objects.filter(',
        '            pk=product.pk, stock__gte=quantity,',
        '        ).update(stock=F("stock") - quantity)',
        '',
        '        if not updated:',
        '            raise OutOfStock(f"موجودی «{product.name}» کافی نیست.")',
        '',
        '        OrderItem.objects.create(',
        '            order=order,',
        '            product=product,',
        '            price=product.price,      # قیمت لحظه خرید',
        '            quantity=quantity,',
        '        )',
        '',
        '    return order',
      ], 'shop/services.py')}
      ${c('python', [
        '# shop/views.py',
        'from django.contrib.auth.decorators import login_required',
        'from .forms import CheckoutForm',
        'from .services import OutOfStock, place_order',
        '',
        '',
        '@login_required',
        'def checkout(request):',
        '    cart = Cart(request)',
        '    if len(cart) == 0:',
        '        messages.info(request, "سبد خرید خالی است.")',
        '        return redirect("shop:product_list")',
        '',
        '    form = CheckoutForm(request.POST or None)',
        '    if request.method == "POST" and form.is_valid():',
        '        try:',
        '            order = place_order(',
        '                user=request.user,',
        '                cart=cart,',
        '                address=form.cleaned_data["address"],',
        '            )',
        '        except OutOfStock as exc:',
        '            messages.error(request, str(exc))',
        '            return redirect("shop:cart_detail")',
        '',
        '        cart.clear()',
        '        messages.success(request, f"سفارش #{order.pk} ثبت شد.")',
        '        return redirect("shop:order_detail", pk=order.pk)',
        '',
        '    return render(request, "shop/checkout.html", {"form": form})',
        '',
        '',
        '@login_required',
        'def order_detail(request, pk):',
        '    order = get_object_or_404(',
        '        Order.objects.prefetch_related("items__product"),',
        '        pk=pk,',
        '        user=request.user,        # ← فقط سفارش خودِ کاربر',
        '    )',
        '    return render(request, "shop/order_detail.html", {"order": order})',
      ], 'view ثبت سفارش')}
      ${callout('danger', 'چرا user=request.user در query؟', 'اگر فقط <code>pk</code> را فیلتر کنید، هر کاربری با تغییر عدد آدرس می‌تواند فاکتور دیگران را ببیند — نمونه کلاسیک IDOR. با آوردن شرط مالکیت داخل query، سفارش دیگران اصلا پیدا نمی‌شود و ۴۰۴ می‌گیرد.')}
      ${quiz('چرا کاهش موجودی را با <code>filter(stock__gte=q).update(stock=F("stock") - q)</code> نوشتیم؟', [
        'چون کوتاه‌تر است.',
        'چون بررسی موجودی و کاهش آن در یک دستور اتمیک دیتابیس انجام می‌شود و دو خرید هم‌زمان نمی‌توانند موجودی را منفی کنند.',
        'چون Django روش دیگری ندارد.',
      ], 1, 'اگر با Python بخوانید و بنویسید، بین خواندن و نوشتن یک فاصله زمانی هست که در آن کاربر دیگری می‌تواند همان موجودی را بردارد. مقدار بازگشتی <code>update()</code> تعداد ردیف‌های تغییریافته است؛ صفر یعنی موجودی کافی نبود.')}
    `),

    s('پروژه عملی', 'مرحله ۱۲: حساب کاربری و داشبورد', 'ثبت‌نام، ورود و صفحه شخصی کاربر.', `
      ${c('python', [
        '# accounts/forms.py',
        'from django import forms',
        'from django.contrib.auth.forms import UserCreationForm',
        'from .models import User',
        '',
        '',
        'class SignUpForm(UserCreationForm):',
        '    email = forms.EmailField(required=True, label="ایمیل")',
        '',
        '    class Meta(UserCreationForm.Meta):',
        '        model = User',
        '        fields = ["username", "email", "phone"]',
        '',
        '    def clean_email(self):',
        '        email = self.cleaned_data["email"].lower()',
        '        if User.objects.filter(email__iexact=email).exists():',
        '            raise forms.ValidationError("این ایمیل قبلا ثبت شده است.")',
        '        return email',
      ], 'accounts/forms.py')}
      ${c('python', [
        '# accounts/views.py',
        'from django.contrib.auth import login',
        'from django.contrib.auth.decorators import login_required',
        'from django.shortcuts import redirect, render',
        'from .forms import SignUpForm',
        '',
        '',
        'def signup(request):',
        '    if request.user.is_authenticated:',
        '        return redirect("blog:home")',
        '',
        '    form = SignUpForm(request.POST or None)',
        '    if request.method == "POST" and form.is_valid():',
        '        user = form.save()',
        '        login(request, user)',
        '        return redirect("accounts:dashboard")',
        '',
        '    return render(request, "accounts/signup.html", {"form": form})',
        '',
        '',
        '@login_required',
        'def dashboard(request):',
        '    return render(request, "accounts/dashboard.html", {',
        '        "posts": request.user.posts.select_related("category"),',
        '        "orders": request.user.orders.prefetch_related("items"),',
        '        "comments": request.user.comments.select_related("post"),',
        '    })',
      ], 'accounts/views.py')}
      ${c('python', [
        '# accounts/urls.py',
        'from django.contrib.auth import views as auth_views',
        'from django.urls import path',
        'from . import views',
        '',
        'app_name = "accounts"',
        '',
        'urlpatterns = [',
        '    path("login/", auth_views.LoginView.as_view(',
        '        template_name="accounts/login.html"), name="login"),',
        '    path("logout/", auth_views.LogoutView.as_view(), name="logout"),',
        '    path("signup/", views.signup, name="signup"),',
        '    path("dashboard/", views.dashboard, name="dashboard"),',
        ']',
      ], 'accounts/urls.py')}
      ${callout('tip', 'داشبورد یعنی چه؟', 'هر چیزی که «مال من» است: مقاله‌های من، سفارش‌های من، نظرهای من. توجه کنید همه‌شان از <code>request.user</code> شروع می‌شوند — پس ذاتا امن‌اند و امکان دیدن داده دیگران وجود ندارد.')}
    `),

    s('پروژه عملی', 'مرحله ۱۳: مدیریت مقاله توسط کاربر', 'ساخت، ویرایش و حذف با بررسی مالکیت.', `
      ${c('python', [
        '# blog/forms.py',
        'class PostForm(forms.ModelForm):',
        '    class Meta:',
        '        model = Post',
        '        fields = ["title", "category", "summary", "body", "cover", "is_published"]',
        '        # ← author عمدا نیست؛ از request.user پر می‌شود',
      ], 'فرم مقاله')}
      ${c('python', [
        '# blog/views.py',
        'from django.core.exceptions import PermissionDenied',
        '',
        '',
        '@login_required',
        'def post_create(request):',
        '    form = PostForm(request.POST or None, request.FILES or None)',
        '    if request.method == "POST" and form.is_valid():',
        '        post = form.save(commit=False)',
        '        post.author = request.user',
        '        post.save()',
        '        messages.success(request, "مقاله ثبت شد.")',
        '        return redirect(post.get_absolute_url())',
        '',
        '    return render(request, "blog/post_form.html", {"form": form})',
        '',
        '',
        '@login_required',
        'def post_edit(request, slug):',
        '    post = get_object_or_404(Post, slug=slug)',
        '    if post.author != request.user:',
        '        raise PermissionDenied',
        '',
        '    form = PostForm(request.POST or None, request.FILES or None, instance=post)',
        '    if request.method == "POST" and form.is_valid():',
        '        form.save()',
        '        messages.success(request, "تغییرات ذخیره شد.")',
        '        return redirect(post.get_absolute_url())',
        '',
        '    return render(request, "blog/post_form.html", {"form": form, "post": post})',
        '',
        '',
        '@login_required',
        '@require_POST',
        'def post_delete(request, slug):',
        '    post = get_object_or_404(Post, slug=slug, author=request.user)',
        '    post.delete()',
        '    messages.success(request, "مقاله حذف شد.")',
        '    return redirect("accounts:dashboard")',
      ], 'CRUD مقاله')}
      ${c('python', [
        '# blog/urls.py — افزودن مسیرها',
        'path("posts/new/", views.post_create, name="post_create"),',
        'path("posts/<slug:slug>/edit/", views.post_edit, name="post_edit"),',
        'path("posts/<slug:slug>/delete/", views.post_delete, name="post_delete"),',
      ], 'مسیرها')}
      ${callout('warn', 'ترتیب را دوباره بررسی کنید', 'مسیر <code>posts/new/</code> باید قبل از <code>posts/&lt;slug:slug&gt;/</code> بیاید، وگرنه Django دنبال مقاله‌ای با slug برابر <code>new</code> می‌گردد و ۴۰۴ می‌دهد.')}
      ${exercise('پیش‌نویس‌های من', 'متوسط', '<p>در داشبورد، مقاله‌های منتشرشده و پیش‌نویس‌ها را جدا نمایش دهید و کنار هر پیش‌نویس دکمه ویرایش بگذارید.</p>', c('python', [
        '@login_required',
        'def dashboard(request):',
        '    posts = request.user.posts.select_related("category")',
        '    return render(request, "accounts/dashboard.html", {',
        '        "published": posts.filter(is_published=True),',
        '        "drafts": posts.filter(is_published=False),',
        '        "orders": request.user.orders.prefetch_related("items"),',
        '    })',
      ], 'راه‌حل'))}
    `),

    s('پروژه عملی', 'مرحله ۱۴: صفحات خطای اختصاصی', 'کاربر نباید صفحه خطای خام ببیند.', `
      ${c('html', [
        '<!-- templates/404.html -->',
        '{% extends "base.html" %}',
        '',
        '{% block title %}صفحه پیدا نشد{% endblock %}',
        '',
        '{% block content %}',
        '  <h1>۴۰۴</h1>',
        '  <p>صفحه‌ای که دنبالش بودید وجود ندارد یا حذف شده است.</p>',
        '  <a href="{% url "blog:home" %}">بازگشت به خانه</a>',
        '{% endblock %}',
      ], 'templates/404.html')}
      ${c('html', [
        '<!-- templates/403.html -->',
        '{% extends "base.html" %}',
        '{% block content %}',
        '  <h1>۴۰۳</h1>',
        '  <p>اجازه دسترسی به این صفحه را ندارید.</p>',
        '{% endblock %}',
      ], 'templates/403.html')}
      ${c('html', [
        '<!-- templates/500.html — بدون extends و بدون متغیر -->',
        '<!doctype html>',
        '<html lang="fa" dir="rtl">',
        '<head><meta charset="utf-8"><title>خطای سرور</title></head>',
        '<body>',
        '  <h1>خطای سرور</h1>',
        '  <p>مشکلی پیش آمده است. لطفا بعدا دوباره تلاش کنید.</p>',
        '  <a href="/">بازگشت به خانه</a>',
        '</body>',
        '</html>',
      ], 'templates/500.html')}
      ${callout('danger', 'قالب ۵۰۰ باید ساده باشد', 'صفحه ۵۰۰ وقتی نمایش داده می‌شود که چیزی خراب شده است — شاید خود context processor یا دیتابیس. اگر <code>{% extends "base.html" %}</code> بنویسید و base به دیتابیس نیاز داشته باشد، خطای دوم رخ می‌دهد و کاربر صفحه سفید می‌بیند.')}
      ${lab('آزمایش صفحات خطا', 'زمان: ۵ دقیقه', [
        { do: c('python', ['# config/settings.py', 'DEBUG = False', 'ALLOWED_HOSTS = ["127.0.0.1", "localhost"]'], 'خاموش‌کردن DEBUG'), why: 'قالب‌های <code>404.html</code> و <code>500.html</code> فقط با <code>DEBUG=False</code> استفاده می‌شوند.' },
        { do: c('bash', ['python manage.py runserver --insecure'], 'اجرا'), why: 'گزینه <code>--insecure</code> باعث می‌شود سرور توسعه با وجود <code>DEBUG=False</code> فایل‌های static را همچنان سرو کند — فقط برای همین آزمایش.' },
        { do: 'آدرس بی‌معنی مثل <code>/no-such-page/</code> را باز کنید تا صفحه ۴۰۴ خودتان را ببینید.' },
        { do: 'بعد از آزمایش، <code>DEBUG</code> را دوباره <code>True</code> کنید.' },
      ], '<p>صفحه ۴۰۴ باید با ظاهر سایت خودتان نمایش داده شود، نه صفحه پیش‌فرض Django.</p>')}
    `),

    s('پروژه عملی', 'مرحله ۱۵: تست‌های پروژه', 'بدون تست، هر تغییر بعدی یک قمار است.', `
      ${c('python', [
        '# blog/tests.py',
        'from django.contrib.auth import get_user_model',
        'from django.test import TestCase',
        'from django.urls import reverse',
        'from .models import Category, Post',
        '',
        'User = get_user_model()',
        '',
        '',
        'class PostPageTests(TestCase):',
        '    @classmethod',
        '    def setUpTestData(cls):',
        '        cls.user = User.objects.create_user("ali", password="pass12345")',
        '        cls.category = Category.objects.create(title="جنگو", slug="django")',
        '        cls.post = Post.objects.create(',
        '            author=cls.user, category=cls.category,',
        '            title="مقاله تست", summary="خلاصه", body="متن",',
        '            is_published=True,',
        '        )',
        '',
        '    def test_slug_is_generated(self):',
        '        self.assertTrue(self.post.slug)',
        '',
        '    def test_detail_page_returns_200(self):',
        '        response = self.client.get(self.post.get_absolute_url())',
        '        self.assertEqual(response.status_code, 200)',
        '        self.assertContains(response, "مقاله تست")',
        '',
        '    def test_draft_post_is_hidden(self):',
        '        draft = Post.objects.create(',
        '            author=self.user, category=self.category,',
        '            title="پیش‌نویس", summary="x", body="y", is_published=False,',
        '        )',
        '        self.assertEqual(self.client.get(draft.get_absolute_url()).status_code, 404)',
        '',
        '    def test_anonymous_cannot_comment(self):',
        '        url = reverse("blog:comment_create", args=[self.post.slug])',
        '        response = self.client.post(url, {"body": "نظر آزمایشی"})',
        '        self.assertEqual(response.status_code, 302)      # به login هدایت شد',
        '',
        '    def test_user_cannot_edit_others_post(self):',
        '        User.objects.create_user("sara", password="pass12345")',
        '        self.client.login(username="sara", password="pass12345")',
        '        url = reverse("blog:post_edit", args=[self.post.slug])',
        '        self.assertEqual(self.client.get(url).status_code, 403)',
      ], 'blog/tests.py')}
      ${c('python', [
        '# shop/tests.py',
        'from django.contrib.auth import get_user_model',
        'from django.test import TestCase',
        'from django.urls import reverse',
        'from .models import Order, Product, ProductCategory',
        '',
        '',
        'class CheckoutTests(TestCase):',
        '    @classmethod',
        '    def setUpTestData(cls):',
        '        cls.user = get_user_model().objects.create_user("ali", password="pass12345")',
        '        category = ProductCategory.objects.create(title="دیجیتال", slug="digital")',
        '        cls.product = Product.objects.create(',
        '            category=category, name="کیبورد", description="x",',
        '            price=900_000, stock=2,',
        '        )',
        '',
        '    def test_add_to_cart_and_checkout_reduces_stock(self):',
        '        self.client.login(username="ali", password="pass12345")',
        '        self.client.post(reverse("shop:cart_add", args=[self.product.id]), {"quantity": 2})',
        '        response = self.client.post(reverse("shop:checkout"), {"address": "تهران"})',
        '',
        '        self.product.refresh_from_db()',
        '        self.assertEqual(self.product.stock, 0)',
        '        self.assertEqual(Order.objects.count(), 1)',
        '        self.assertEqual(response.status_code, 302)',
        '',
        '    def test_cannot_order_more_than_stock(self):',
        '        self.client.login(username="ali", password="pass12345")',
        '        self.client.post(reverse("shop:cart_add", args=[self.product.id]), {"quantity": 99})',
        '        self.client.post(reverse("shop:checkout"), {"address": "تهران"})',
        '',
        '        self.product.refresh_from_db()',
        '        self.assertGreaterEqual(self.product.stock, 0)',
        '',
        '    def test_user_cannot_see_others_order(self):',
        '        other = get_user_model().objects.create_user("sara", password="pass12345")',
        '        order = Order.objects.create(user=other, address="مشهد")',
        '        self.client.login(username="ali", password="pass12345")',
        '        url = reverse("shop:order_detail", args=[order.pk])',
        '        self.assertEqual(self.client.get(url).status_code, 404)',
      ], 'shop/tests.py')}
      ${c('bash', ['python manage.py test', 'python manage.py test blog.tests.PostPageTests -v 2'], 'اجرای تست‌ها')}
      ${callout('tip', 'چه چیزی را تست کنیم؟', 'اولویت با «رفتارهایی که خرابی‌شان گران است»: دسترسی‌ها، منطق پول و موجودی، و مسیرهای اصلی کاربر. تست‌کردن اینکه <code>CharField</code> رشته ذخیره می‌کند ارزشی ندارد — آن را Django تضمین کرده است.')}
    `),

    s('پروژه عملی', 'نقطه کنترل پروژه', 'قبل از رفتن به بخش حرفه‌ای‌سازی.', `
      ${checklist('سناریوی کامل کاربر را روی پروژه خودتان اجرا کنید', [
        'صفحه اصلی باز می‌شود و مقاله‌های نمونه دیده می‌شوند.',
        'صفحه جزئیات مقاله، نظرها و فرم نظر را نشان می‌دهد.',
        'کاربر مهمان نمی‌تواند نظر بدهد و به صفحه ورود هدایت می‌شود.',
        'ثبت‌نام، ورود و خروج کار می‌کند.',
        'فروشگاه محصولات را با فیلتر دسته نشان می‌دهد.',
        'افزودن به سبد، حذف از سبد و شمارنده سبد در header درست کار می‌کند.',
        'ثبت سفارش موجودی را کم می‌کند و سبد را خالی می‌کند.',
        'کاربر نمی‌تواند سفارش یا مقاله کاربر دیگر را ببیند یا ویرایش کند.',
        'صفحه ۴۰۴ اختصاصی نمایش داده می‌شود.',
        '<code>python manage.py test</code> با <code>OK</code> تمام می‌شود.',
      ])}
      ${tbl(['اگر این را دیدید', 'احتمالا این است'], [
        ['<code>NoReverseMatch</code> در header', 'یکی از appها <code>app_name</code> ندارد یا مسیر هنوز ساخته نشده.'],
        ['سبد همیشه خالی می‌ماند', '<code>session.modified = True</code> جا افتاده.'],
        ['شمارنده سبد در header نیست', 'context processor در <code>settings.py</code> ثبت نشده.'],
        ['<code>/shop/cart/</code> خطای ۴۰۴ می‌دهد', 'الگوی <code>&lt;slug:slug&gt;</code> بالاتر از <code>cart/</code> است.'],
        ['تصویر آپلودی نمایش داده نمی‌شود', '<code>MEDIA_URL</code> در <code>urls.py</code> اضافه نشده یا <code>{% static %}</code> به‌جای <code>.url</code> استفاده شده.'],
        ['خطای Pillow', '<code>pip install pillow</code>.'],
      ])}
      ${exercise('گسترش پروژه', 'چالشی', `
        <p>سه قابلیت زیر را خودتان اضافه کنید (بدون راه‌حل آماده):</p>
        <ol>
          <li><strong>تغییر تعداد در سبد:</strong> فرمی کنار هر آیتم که تعداد را به‌روزرسانی کند (از <code>override=True</code> در <code>Cart.add</code> استفاده کنید).</li>
          <li><strong>علاقه‌مندی‌ها:</strong> مدل <code>ManyToManyField</code> بین کاربر و محصول، همراه دکمه افزودن/حذف.</li>
          <li><strong>لغو سفارش:</strong> کاربر بتواند سفارش <code>pending</code> خودش را لغو کند و موجودی به انبار برگردد — حتما داخل تراکنش.</li>
        </ol>`,
        '<p>راهنمای طراحی: برای مورد سوم یک تابع <code>cancel_order(order)</code> در <code>services.py</code> بنویسید که با <code>@transaction.atomic</code> وضعیت را به <code>CANCELED</code> ببرد و برای هر آیتم <code>update(stock=F("stock") + item.quantity)</code> بزند. حتما بررسی کنید سفارش متعلق به همان کاربر و وضعیتش <code>pending</code> باشد، وگرنه کاربر می‌تواند با لغو مکرر، موجودی را بی‌نهایت زیاد کند.</p>')}
    `)
  );
})(window);
